---
- name: Apply OS hardening
  hosts: localhost
  become: yes  # This is important for system-level changes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
  vars:
    ansible_role_name: os_hardening
